{
  "openapi": "3.0.2",
  "info": {
    "title": "F1 API",
    "description": "An easier way to use the [ergast.com](https://ergast.com/mrd/) F1 API, with correct types!",
    "license": {
      "name": "MIT",
      "url": "https://github.com/niek-o/F1API/blob/main/LICENSE.md"
    },
    "version": "1.8.0",
    "x-logo": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/New_era_F1_logo.png"
    }
  },
  "paths": {
    "/calendar/{season}": {
      "get": {
        "tags": [
          "Season"
        ],
        "summary": "Get Calendar By Season",
        "operationId": "get_calendar_by_season",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "integer"
            },
            "name": "season",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Calendar"
                },
                "example": {
                  "timestamp": 1669979281.7311087,
                  "events": [
                    {
                      "season": 2022,
                      "round": 1,
                      "url": "https://en.wikipedia.org/wiki/2022_Bahrain_Grand_Prix",
                      "raceName": "Bahrain Grand Prix",
                      "Circuit": {
                        "circuitId": "bahrain",
                        "url": "https://en.wikipedia.org/wiki/Bahrain_International_Circuit",
                        "circuitName": "Bahrain International Circuit",
                        "Location": {
                          "lat": 26.0325,
                          "long": 50.5106,
                          "locality": "Sakhir",
                          "country": "Bahrain"
                        }
                      },
                      "date": "2022-03-20",
                      "time": "15:00:00Z",
                      "FirstPractice": {
                        "date": "2022-03-18",
                        "time": "12:00:00Z"
                      },
                      "SecondPractice": {
                        "date": "2022-03-18",
                        "time": "15:00:00Z"
                      },
                      "ThirdPractice": {
                        "date": "2022-03-19",
                        "time": "12:00:00Z"
                      },
                      "Qualifying": {
                        "date": "2022-03-19",
                        "time": "15:00:00Z"
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Calendar not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/event/next": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Get Next Race",
        "operationId": "get_next_race",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NextEvent"
                },
                "example": {
                  "timestamp": 1669979205.6921754,
                  "season": 2023,
                  "round": 1
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/event/previous": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Get Previous Race",
        "operationId": "get_previous_race",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NextEvent"
                },
                "example": {
                  "timestamp": 1669979205.6921754,
                  "season": 2023,
                  "round": 1
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/event/{season}/{race}": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Get Event Details",
        "operationId": "get_event_details",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "integer"
            },
            "name": "season",
            "in": "path"
          },
          {
            "required": true,
            "schema": {
              "title": "Race",
              "type": "integer"
            },
            "name": "race",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Event"
                },
                "example": {
                  "timestamp": 1669979237.0388148,
                  "season": 2022,
                  "round": 22,
                  "url": "https://en.wikipedia.org/wiki/2022_Abu_Dhabi_Grand_Prix",
                  "raceName": "Abu Dhabi Grand Prix",
                  "Circuit": {
                    "circuitId": "yas_marina",
                    "url": "https://en.wikipedia.org/wiki/Yas_Marina_Circuit",
                    "circuitName": "Yas Marina Circuit",
                    "Location": {
                      "lat": 24.4672,
                      "long": 54.6031,
                      "locality": "Abu Dhabi",
                      "country": "UAE"
                    }
                  },
                  "date": "2022-11-20",
                  "time": "13:00:00Z",
                  "FirstPractice": {
                    "date": "2022-11-18",
                    "time": "10:00:00Z"
                  },
                  "SecondPractice": {
                    "date": "2022-11-18",
                    "time": "13:00:00Z"
                  },
                  "ThirdPractice": {
                    "date": "2022-11-19",
                    "time": "11:00:00Z"
                  },
                  "Qualifying": {
                    "date": "2022-11-19",
                    "time": "14:00:00Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Event not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/circuits": {
      "get": {
        "tags": [
          "Circuits"
        ],
        "summary": "Get Circuits",
        "operationId": "get_circuits",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Circuits"
                },
                "example": {
                  "timestamp": 1669978972.4221265,
                  "circuits": [
                    {
                      "circuitId": "zandvoort",
                      "url": "https://en.wikipedia.org/wiki/Circuit_Zandvoort",
                      "circuitName": "Circuit Park Zandvoort",
                      "Location": {
                        "lat": 52.3888,
                        "long": 4.54092,
                        "locality": "Zandvoort",
                        "country": "Netherlands"
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Circuits not found"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/circuits/{season}": {
      "get": {
        "tags": [
          "Circuits",
          "Season"
        ],
        "summary": "Get Circuits By Season",
        "operationId": "get_circuits_by_season",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "string"
            },
            "name": "season",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Circuits"
                },
                "example": {
                  "timestamp": 1669978972.4221265,
                  "circuits": [
                    {
                      "circuitId": "zandvoort",
                      "url": "https://en.wikipedia.org/wiki/Circuit_Zandvoort",
                      "circuitName": "Circuit Park Zandvoort",
                      "Location": {
                        "lat": 52.3888,
                        "long": 4.54092,
                        "locality": "Zandvoort",
                        "country": "Netherlands"
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Circuits not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/circuit/{circuit_id}": {
      "get": {
        "tags": [
          "Circuits"
        ],
        "summary": "Get Circuit By Id",
        "operationId": "get_circuit_by_id",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Circuit Id",
              "type": "string"
            },
            "name": "circuit_id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Circuit"
                },
                "example": {
                  "timestamp": 1669978998.3723269,
                  "circuitId": "zandvoort",
                  "url": "https://en.wikipedia.org/wiki/Circuit_Zandvoort",
                  "circuitName": "Circuit Park Zandvoort",
                  "Location": {
                    "lat": 52.3888,
                    "long": 4.54092,
                    "locality": "Zandvoort",
                    "country": "Netherlands"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Circuit not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/constructors": {
      "get": {
        "tags": [
          "Constructors"
        ],
        "summary": "Get Constructors",
        "operationId": "get_constructors",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Constructors"
                },
                "example": {
                  "timestamp": 1669978869.9509943,
                  "constructors": [
                    {
                      "constructorId": "red_bull",
                      "url": "https://en.wikipedia.org/wiki/Red_Bull_Racing",
                      "name": "Red Bull",
                      "nationality": "Austrian"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Constructors not found"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/constructors/{season}": {
      "get": {
        "tags": [
          "Constructors",
          "Season"
        ],
        "summary": "Get Constructors By Season",
        "operationId": "get_constructors_by_season",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "string"
            },
            "name": "season",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Constructors"
                },
                "example": {
                  "timestamp": 1669978869.9509943,
                  "constructors": [
                    {
                      "constructorId": "red_bull",
                      "url": "https://en.wikipedia.org/wiki/Red_Bull_Racing",
                      "name": "Red Bull",
                      "nationality": "Austrian"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Constructors not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/constructor/{constructor_id}": {
      "get": {
        "tags": [
          "Constructors"
        ],
        "summary": "Get Constructor By Id",
        "operationId": "get_constructor_by_id",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Constructor Id",
              "type": "string"
            },
            "name": "constructor_id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Constructor"
                },
                "example": {
                  "timestamp": 1669978904.85484,
                  "constructorId": "red_bull",
                  "url": "https://en.wikipedia.org/wiki/Red_Bull_Racing",
                  "name": "Red Bull",
                  "nationality": "Austrian"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Constructor not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/drivers": {
      "get": {
        "tags": [
          "Drivers"
        ],
        "summary": "Get Drivers",
        "operationId": "get_drivers",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Drivers"
                },
                "example": {
                  "timestamp": 1669978500.8190658,
                  "drivers": [
                    {
                      "driverId": "max_verstappen",
                      "url": "https://en.wikipedia.org/wiki/Max_Verstappen",
                      "givenName": "Max",
                      "familyName": "Verstappen",
                      "dateOfBirth": "1997-09-30",
                      "nationality": "Dutch",
                      "permanentNumber": 33,
                      "code": "VER"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Drivers not found"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/drivers/{season}": {
      "get": {
        "tags": [
          "Drivers",
          "Season"
        ],
        "summary": "Get Drivers By Season",
        "operationId": "get_drivers_by_season",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "integer"
            },
            "name": "season",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Drivers"
                },
                "example": {
                  "timestamp": 1669978500.8190658,
                  "drivers": [
                    {
                      "driverId": "max_verstappen",
                      "url": "https://en.wikipedia.org/wiki/Max_Verstappen",
                      "givenName": "Max",
                      "familyName": "Verstappen",
                      "dateOfBirth": "1997-09-30",
                      "nationality": "Dutch",
                      "permanentNumber": 33,
                      "code": "VER"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Drivers not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/driver/{driver_id}": {
      "get": {
        "tags": [
          "Drivers"
        ],
        "summary": "Get Driver By Id",
        "operationId": "get_driver_by_id",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Driver Id",
              "type": "string"
            },
            "name": "driver_id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Driver"
                },
                "example": {
                  "timestamp": 1669978482.9627361,
                  "driverId": "max_verstappen",
                  "url": "https://en.wikipedia.org/wiki/Max_Verstappen",
                  "givenName": "Max",
                  "familyName": "Verstappen",
                  "dateOfBirth": "1997-09-30",
                  "nationality": "Dutch",
                  "permanentNumber": 33,
                  "code": "VER"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Driver not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/results/race/{season}/{race}": {
      "get": {
        "tags": [
          "Results"
        ],
        "summary": "Get Race Results",
        "operationId": "get_race_results",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "integer"
            },
            "name": "season",
            "in": "path"
          },
          {
            "required": true,
            "schema": {
              "title": "Race",
              "type": "integer"
            },
            "name": "race",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RaceResults"
                },
                "example": {
                  "timestamp": 1669978263.7017405,
                  "results": [
                    {
                      "number": 1,
                      "position": 1,
                      "positionText": "1",
                      "points": 25,
                      "Driver": {
                        "driverId": "max_verstappen",
                        "url": "https://en.wikipedia.org/wiki/Max_Verstappen",
                        "givenName": "Max",
                        "familyName": "Verstappen",
                        "dateOfBirth": "1997-09-30",
                        "nationality": "Dutch",
                        "permanentNumber": 33,
                        "code": "VER"
                      },
                      "Constructor": {
                        "constructorId": "red_bull",
                        "url": "https://en.wikipedia.org/wiki/Red_Bull_Racing",
                        "name": "Red Bull",
                        "nationality": "Austrian"
                      },
                      "grid": 1,
                      "laps": 58,
                      "status": "Finished",
                      "Time": {
                        "time": "1:27:45.914",
                        "millis": "5265914"
                      },
                      "FastestLap": {
                        "rank": 6,
                        "lap": 54,
                        "Time": {
                          "time": "1:29.392"
                        },
                        "AverageSpeed": {
                          "units": "kph",
                          "speed": 212.676
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Race results not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/results/qualifying/{season}/{race}": {
      "get": {
        "tags": [
          "Results"
        ],
        "summary": "Get Qualifying Results",
        "operationId": "get_qualifying_results",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "integer"
            },
            "name": "season",
            "in": "path"
          },
          {
            "required": true,
            "schema": {
              "title": "Race",
              "type": "integer"
            },
            "name": "race",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QualifyingResults"
                },
                "example": {
                  "timestamp": 1669978379.0060742,
                  "results": [
                    {
                      "number": 1,
                      "position": 1,
                      "Driver": {
                        "driverId": "max_verstappen",
                        "url": "https://en.wikipedia.org/wiki/Max_Verstappen",
                        "givenName": "Max",
                        "familyName": "Verstappen",
                        "dateOfBirth": "1997-09-30",
                        "nationality": "Dutch",
                        "permanentNumber": 33,
                        "code": "VER"
                      },
                      "Constructor": {
                        "constructorId": "red_bull",
                        "url": "https://en.wikipedia.org/wiki/Red_Bull_Racing",
                        "name": "Red Bull",
                        "nationality": "Austrian"
                      },
                      "Q1": "1:24.754",
                      "Q2": "1:24.622",
                      "Q3": "1:23.824"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Qualifying results not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/results/standings/drivers/{season}": {
      "get": {
        "tags": [
          "Results",
          "Season"
        ],
        "summary": "Get Driver Standings By Season",
        "operationId": "get_driver_standings_by_season",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "integer"
            },
            "name": "season",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DriverStandings"
                },
                "example": {
                  "timestamp": 1669977611.5538518,
                  "standings": [
                    {
                      "position": 1,
                      "positionText": "1",
                      "points": 454,
                      "wins": 15,
                      "Driver": {
                        "driverId": "max_verstappen",
                        "url": "https://en.wikipedia.org/wiki/Max_Verstappen",
                        "givenName": "Max",
                        "familyName": "Verstappen",
                        "dateOfBirth": "1997-09-30",
                        "nationality": "Dutch",
                        "permanentNumber": 33,
                        "code": "VER"
                      },
                      "Constructors": [
                        {
                          "constructorId": "red_bull",
                          "url": "https://en.wikipedia.org/wiki/Red_Bull_Racing",
                          "name": "Red Bull",
                          "nationality": "Austrian"
                        }
                      ]
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Standings not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/results/standings/constructors/{season}": {
      "get": {
        "tags": [
          "Results",
          "Season"
        ],
        "summary": "Get Constructor Standings By Season",
        "operationId": "get_constructor_standings_by_season",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Season",
              "type": "integer"
            },
            "name": "season",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConstructorStandings"
                },
                "example": {
                  "timestamp": 1669977723.5049899,
                  "standings": [
                    {
                      "position": 1,
                      "positionText": "1",
                      "points": 759,
                      "wins": 17,
                      "Constructor": {
                        "constructorId": "red_bull",
                        "url": "https://en.wikipedia.org/wiki/Red_Bull_Racing",
                        "name": "Red Bull",
                        "nationality": "Austrian"
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Standings not found"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "message": "Service unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/test": {
      "get": {
        "summary": "Test",
        "operationId": "test",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AverageSpeed": {
        "title": "AverageSpeed",
        "required": [
          "units",
          "speed"
        ],
        "type": "object",
        "properties": {
          "units": {
            "title": "Units",
            "type": "string"
          },
          "speed": {
            "title": "Speed",
            "type": "number"
          }
        }
      },
      "Calendar": {
        "title": "Calendar",
        "required": [
          "events"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "events": {
            "title": "Events",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Event"
            }
          }
        }
      },
      "Circuit": {
        "title": "Circuit",
        "required": [
          "circuitId",
          "url",
          "circuitName",
          "Location"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "circuitId": {
            "title": "Circuitid",
            "type": "string"
          },
          "url": {
            "title": "Url",
            "type": "string"
          },
          "circuitName": {
            "title": "Circuitname",
            "type": "string"
          },
          "Location": {
            "$ref": "#/components/schemas/Location"
          }
        }
      },
      "Circuits": {
        "title": "Circuits",
        "required": [
          "circuits"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "circuits": {
            "title": "Circuits",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Circuit"
            }
          }
        }
      },
      "Constructor": {
        "title": "Constructor",
        "required": [
          "constructorId",
          "url",
          "name",
          "nationality"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "constructorId": {
            "title": "Constructorid",
            "type": "string"
          },
          "url": {
            "title": "Url",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "nationality": {
            "title": "Nationality",
            "type": "string"
          }
        }
      },
      "ConstructorStanding": {
        "title": "ConstructorStanding",
        "required": [
          "position",
          "positionText",
          "points",
          "wins",
          "Constructor"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "position": {
            "title": "Position",
            "type": "integer"
          },
          "positionText": {
            "title": "Positiontext",
            "type": "string"
          },
          "points": {
            "title": "Points",
            "type": "integer"
          },
          "wins": {
            "title": "Wins",
            "type": "integer"
          },
          "Constructor": {
            "$ref": "#/components/schemas/Constructor"
          }
        }
      },
      "ConstructorStandings": {
        "title": "ConstructorStandings",
        "required": [
          "standings"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "standings": {
            "title": "Standings",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ConstructorStanding"
            }
          }
        }
      },
      "Constructors": {
        "title": "Constructors",
        "required": [
          "constructors"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "constructors": {
            "title": "Constructors",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Constructor"
            }
          }
        }
      },
      "Driver": {
        "title": "Driver",
        "required": [
          "driverId",
          "url",
          "givenName",
          "familyName",
          "dateOfBirth",
          "nationality"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "driverId": {
            "title": "Driverid",
            "type": "string"
          },
          "url": {
            "title": "Url",
            "type": "string"
          },
          "givenName": {
            "title": "Givenname",
            "type": "string"
          },
          "familyName": {
            "title": "Familyname",
            "type": "string"
          },
          "dateOfBirth": {
            "title": "Dateofbirth",
            "type": "string"
          },
          "nationality": {
            "title": "Nationality",
            "type": "string"
          },
          "permanentNumber": {
            "title": "Permanentnumber",
            "type": "integer"
          },
          "code": {
            "title": "Code",
            "type": "string"
          }
        }
      },
      "DriverStanding": {
        "title": "DriverStanding",
        "required": [
          "position",
          "positionText",
          "points",
          "wins",
          "Driver",
          "Constructors"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "position": {
            "title": "Position",
            "type": "integer"
          },
          "positionText": {
            "title": "Positiontext",
            "type": "string"
          },
          "points": {
            "title": "Points",
            "type": "integer"
          },
          "wins": {
            "title": "Wins",
            "type": "integer"
          },
          "Driver": {
            "$ref": "#/components/schemas/Driver"
          },
          "Constructors": {
            "title": "Constructors",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Constructor"
            }
          }
        }
      },
      "DriverStandings": {
        "title": "DriverStandings",
        "required": [
          "standings"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "standings": {
            "title": "Standings",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/DriverStanding"
            }
          }
        }
      },
      "Drivers": {
        "title": "Drivers",
        "required": [
          "drivers"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "drivers": {
            "title": "Drivers",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Driver"
            }
          }
        }
      },
      "Event": {
        "title": "Event",
        "required": [
          "season",
          "round",
          "url",
          "raceName",
          "Circuit",
          "date"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "season": {
            "title": "Season",
            "type": "integer"
          },
          "round": {
            "title": "Round",
            "type": "integer"
          },
          "url": {
            "title": "Url",
            "type": "string"
          },
          "raceName": {
            "title": "Racename",
            "type": "string"
          },
          "Circuit": {
            "$ref": "#/components/schemas/Circuit"
          },
          "date": {
            "title": "Date",
            "type": "string"
          },
          "time": {
            "title": "Time",
            "type": "string"
          },
          "FirstPractice": {
            "$ref": "#/components/schemas/Session"
          },
          "SecondPractice": {
            "$ref": "#/components/schemas/Session"
          },
          "ThirdPractice": {
            "$ref": "#/components/schemas/Session"
          },
          "Qualifying": {
            "$ref": "#/components/schemas/Session"
          }
        }
      },
      "FastestLap": {
        "title": "FastestLap",
        "required": [
          "rank",
          "lap",
          "Time",
          "AverageSpeed"
        ],
        "type": "object",
        "properties": {
          "rank": {
            "title": "Rank",
            "type": "integer"
          },
          "lap": {
            "title": "Lap",
            "type": "integer"
          },
          "Time": {
            "$ref": "#/components/schemas/Time"
          },
          "AverageSpeed": {
            "$ref": "#/components/schemas/AverageSpeed"
          }
        }
      },
      "HTTPValidationError": {
        "title": "HTTPValidationError",
        "type": "object",
        "properties": {
          "detail": {
            "title": "Detail",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            }
          }
        }
      },
      "Location": {
        "title": "Location",
        "required": [
          "lat",
          "long",
          "locality",
          "country"
        ],
        "type": "object",
        "properties": {
          "lat": {
            "title": "Lat",
            "type": "number"
          },
          "long": {
            "title": "Long",
            "type": "number"
          },
          "locality": {
            "title": "Locality",
            "type": "string"
          },
          "country": {
            "title": "Country",
            "type": "string"
          }
        }
      },
      "Message": {
        "title": "Message",
        "required": [
          "message"
        ],
        "type": "object",
        "properties": {
          "message": {
            "title": "Message",
            "type": "string"
          }
        }
      },
      "NextEvent": {
        "title": "NextEvent",
        "required": [
          "season",
          "round"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "season": {
            "title": "Season",
            "type": "integer"
          },
          "round": {
            "title": "Round",
            "type": "integer"
          }
        }
      },
      "QualifyingResult": {
        "title": "QualifyingResult",
        "required": [
          "number",
          "position",
          "Driver",
          "Constructor"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "number": {
            "title": "Number",
            "type": "integer"
          },
          "position": {
            "title": "Position",
            "type": "integer"
          },
          "Driver": {
            "$ref": "#/components/schemas/Driver"
          },
          "Constructor": {
            "$ref": "#/components/schemas/Constructor"
          },
          "Q1": {
            "title": "Q1",
            "type": "string"
          },
          "Q2": {
            "title": "Q2",
            "type": "string"
          },
          "Q3": {
            "title": "Q3",
            "type": "string"
          }
        }
      },
      "QualifyingResults": {
        "title": "QualifyingResults",
        "required": [
          "results"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "results": {
            "title": "Results",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/QualifyingResult"
            }
          }
        }
      },
      "RaceResult": {
        "title": "RaceResult",
        "required": [
          "number",
          "position",
          "positionText",
          "points",
          "Driver",
          "Constructor",
          "grid",
          "laps",
          "status"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "number": {
            "title": "Number",
            "type": "integer"
          },
          "position": {
            "title": "Position",
            "type": "integer"
          },
          "positionText": {
            "title": "Positiontext",
            "type": "string"
          },
          "points": {
            "title": "Points",
            "type": "number"
          },
          "Driver": {
            "$ref": "#/components/schemas/Driver"
          },
          "Constructor": {
            "$ref": "#/components/schemas/Constructor"
          },
          "grid": {
            "title": "Grid",
            "type": "integer"
          },
          "laps": {
            "title": "Laps",
            "type": "integer"
          },
          "status": {
            "title": "Status",
            "type": "string"
          },
          "Time": {
            "$ref": "#/components/schemas/Time"
          },
          "FastestLap": {
            "$ref": "#/components/schemas/FastestLap"
          }
        }
      },
      "RaceResults": {
        "title": "RaceResults",
        "required": [
          "results"
        ],
        "type": "object",
        "properties": {
          "timestamp": {
            "title": "Timestamp",
            "type": "number"
          },
          "results": {
            "title": "Results",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RaceResult"
            }
          }
        }
      },
      "Session": {
        "title": "Session",
        "type": "object",
        "properties": {
          "date": {
            "title": "Date",
            "type": "string"
          },
          "time": {
            "title": "Time",
            "type": "string"
          }
        }
      },
      "Time": {
        "title": "Time",
        "required": [
          "time"
        ],
        "type": "object",
        "properties": {
          "time": {
            "title": "Time",
            "type": "string"
          },
          "millis": {
            "title": "Millis",
            "type": "string"
          }
        }
      },
      "ValidationError": {
        "title": "ValidationError",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "type": "object",
        "properties": {
          "loc": {
            "title": "Location",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            }
          },
          "msg": {
            "title": "Message",
            "type": "string"
          },
          "type": {
            "title": "Error Type",
            "type": "string"
          }
        }
      }
    }
  }
}